"""empty message

Revision ID: 2fa0f94a6c3b
Revises: 403c4cc76cf4
Create Date: 2026-07-02 16:21:55.382867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fa0f94a6c3b'
down_revision: Union[str, None] = '403c4cc76cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification_time', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_time')
    # ### end Alembic commands ###